#server:
#  port: 8090
#  servlet:
#    context-path: /springboot
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 0000
#    url: jdbc:mysql://localhost:3306/codefirstdb
#    username: Ruslan
#
#jpa:
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL5Dialect
#  hibernate:
#    ddl-auto: create-drop
#  show-sql: true